### ISSUE TITLE
Failure case minimization

### ISSUE THREAD

**Issue by rasuru** [syberside/Activatory#50]
Amazing project, keep it up! I would love to see failure case minimization in order to make the process of debugging easier. Will Activatory support it?

**Comment by syberside** [comment]
Hi! Thank you for feedback. Could you please add more details about “failure case minimization“? I am not sure that I understand what do you mean.

**Comment by rasuru** [comment]
Oh well, by that I meant something like what QuickCheck has (if I am not wrong). It generates bunch of tests, but if something fails it simplifies the random data to small human understandable scales. Maybe watching this talk on YouTube will help: https://www.youtube.com/watch?v=mg5BeeYGjY0&t=994s. Search in the beginning :)

**Comment by rasuru** [comment]
A better explanation from the author of QuickCheck: https://www.youtube.com/watch?v=AfaNEebCDos

**Comment by syberside** [comment]
Ok, I got it.

I don't have plans on such functionality right now.
I believe that it will be useful. But actually, I think that it should be implemented as a separate package based on Activatory.
Are you the one who will implement it? ;)  I could help you with required changes on Activatory side.

BTW, As I can see, there were attempts to implement QuickCheck:
- https://github.com/polux/propcheck
- https://github.com/rebbix/dart-quickcheck

Those projects look abandoned, but maybe authors could help you.

**Comment by rasuru** [comment]
Oh, okay. Thank you for researching, that's a good proposal :D I don't know, after I finish with my app, which will take months to finish, maybe I will try! Why not? :smile:
